services:
  _defaults:
    autowire: true
    autoconfigure: true

  Benedekb\OpenAPI\:
    resource: '../src/'
    exclude:
      - '../src/Component/Schema'
      - '../src/Component/Enum'
      - '../src/Component/Attribute'

  Benedekb\OpenAPI\Command\GenerateOpenAPICommand:
    arguments:
      $filePath: '%openapi.file_path%'