services:
  _defaults:
    autowire: true
    autoconfigure: true

  Benedekb\OpenAPI\:
    resource: '../src/'
    exclude:
      - '../src/Component/Schema'
      - '../src/Component/Enum'
      - '../src/Component/Attribute'

  Benedekb\OpenAPI\Command\GenerateOpenAPICommand:
    arguments:
      $filePath: '%openapi.file_path%'

  Benedekb\OpenAPI\Component\Configuration\GenerationConfig:
    arguments:
      $skippedRoutes: '%openapi.skipped_routes%'
      $openApiVersion: '%openapi.oas_version%'
      $specificationVersion: '%openapi.version%'
      $serviceName: '%openapi.name%'
      $serviceDescription: '%openapi.description%'